version: "3.3"

services:
  mysql:
    image: 'mysql:5.7.30'
    container_name: devmod_mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysql_data: ~
